name: build songbook

on:
  push:
    tags:
      - v* 

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: 'true'
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install brew packages
      run: |
        brew install gs xpdf
    - name: check pdfs are present
      run: |
        find . -name '*.pdf' 
    - name: build frontmatter
      run: |
        sh scripts/frontmatter.sh
    - name: build songbook
      run: |
        sh scripts/gs.sh songbook.pdf
    - name: check songbook is present
      run: |
        ls -lh songbook.pdf
        pdfinfo -box -meta songbook.pdf
        
    - name: upload pdf binary
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
          name: songbook.pdf
          path: songbook.pdf
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: songbook.pdf
